---
name: Nagios-Spool-Writer
version: v0.0.1
author:
  - 'Danijel Tašov <dt@korn.shell.la>'
abstract: drop check results into nagios' spool dir
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Temp: 0
  Moose: 0
  Test::More: 0
  version: 0
configure_requires:
  Module::Build: 0.35
provides:
  Nagios::Spool::Writer:
    file: lib/Nagios/Spool/Writer.pm
    version: v0.0.1
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
